name: Generate Snake Contibution Grid

on:
  workflow_dispatch:

  schedule:
    - cron: '* */12 * * *'

jobs:
  build:
    name: Job to update svg
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: zoispag
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  